#
# Ref:
#   https://docs.travis-ci.com/user/languages/python/
#

language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
# - pipenv sync

install:
  - pip install -e .

script:
  - make test-detailed test-bash

after_success:
  - coveralls
